import React, { useState, useEffect } from 'react';
import {
    Modal,
    View,
    StyleSheet,
    TextInput,
    TouchableOpacity,
    ScrollView,
    KeyboardAvoidingView,
    Platform,
    Alert,
} from 'react-native';
import { Text } from './Themed';
import { Palette } from '@/constants/Colors';
import { Ionicons } from '@expo/vector-icons';
import { LaborProfile, LaborType } from '@/types/farm';

interface LaborModalProps {
    visible: boolean;
    onClose: () => void;
    onSave: (worker: LaborProfile) => Promise<void>;
    initialType?: LaborType;
}

export function LaborModal({ visible, onClose, onSave, initialType = 'Daily' }: LaborModalProps) {
    const [name, setName] = useState('');
    const [phone, setPhone] = useState('');
    const [type, setType] = useState<LaborType>(initialType);
    const [baseWage, setBaseWage] = useState('');
    const [notes, setNotes] = useState('');
    const [isSaving, setIsSaving] = useState(false);

    useEffect(() => {
        if (visible) {
            setType(initialType);
            setIsSaving(false);
        }
    }, [visible, initialType]);

    const handleSave = async () => {
        if (!name.trim()) {
            Alert.alert('Error', 'Please enter a name');
            return;
        }

        if (isSaving) return;

        try {
            setIsSaving(true);
            const worker: LaborProfile = {
                id: '', // Will be generated by Supabase
                name: name.trim(),
                phone: phone.trim(),
                type,
                baseWage: baseWage ? parseFloat(baseWage) : undefined,
                isActive: true,
                startDate: new Date().toISOString().split('T')[0],
                notes: notes.trim(),
            };

            await onSave(worker);
            reset();
            onClose();
        } catch (error) {
            Alert.alert('Error', 'Failed to save staff member');
        } finally {
            setIsSaving(false);
        }
    };

    const reset = () => {
        setName('');
        setPhone('');
        setType(initialType);
        setBaseWage('');
        setNotes('');
    };

    return (
        <Modal
            visible={visible}
            animationType="slide"
            transparent={true}
            onRequestClose={onClose}
        >
            <View style={styles.modalOverlay}>
                <KeyboardAvoidingView
                    behavior={Platform.OS === 'ios' ? 'padding' : undefined}
                    style={styles.modalContent}
                >
                    <View style={styles.header}>
                        <Text style={styles.title}>Add New Staff</Text>
                        <TouchableOpacity onPress={onClose} style={styles.closeButton} disabled={isSaving}>
                            <Ionicons name="close" size={24} color={Palette.text} />
                        </TouchableOpacity>
                    </View>

                    <ScrollView 
                        showsVerticalScrollIndicator={false} 
                        style={styles.form}
                        keyboardShouldPersistTaps="handled"
                    >
                        <View style={styles.inputGroup}>
                            <Text style={styles.label}>Full Name</Text>
                            <TextInput
                                style={styles.input}
                                value={name}
                                onChangeText={setName}
                                placeholder="Enter worker name"
                                placeholderTextColor={Palette.textSecondary + '80'}
                                editable={!isSaving}
                            />
                        </View>

                        <View style={styles.inputGroup}>
                            <Text style={styles.label}>Staff Type</Text>
                            <View style={styles.typeSelector}>
                                {(['Daily', 'Annual', 'Contract'] as LaborType[]).map((t) => (
                                    <TouchableOpacity
                                        key={t}
                                        style={[styles.typeButton, type === t && styles.activeTypeButton]}
                                        onPress={() => setType(t)}
                                        disabled={isSaving}
                                    >
                                        <Text style={[styles.typeButtonText, type === t && styles.activeTypeButtonText]}>
                                            {t}
                                        </Text>
                                    </TouchableOpacity>
                                ))}
                            </View>
                        </View>

                        <View style={styles.inputGroup}>
                            <Text style={styles.label}>
                                {type === 'Daily' ? 'Daily Wage (₹)' : type === 'Annual' ? 'Annual Salary (₹)' : 'Contract Head Fee (₹)'}
                            </Text>
                            <TextInput
                                style={styles.input}
                                value={baseWage}
                                onChangeText={setBaseWage}
                                keyboardType="numeric"
                                placeholder="0.00"
                                editable={!isSaving}
                                placeholderTextColor={Palette.textSecondary + '80'}
                            />
                            <Text style={styles.hint}>
                                {type === 'Daily' ? 'Fixed rate paid for every day present.' : type === 'Annual' ? 'Used to derive daily deduction amount.' : 'Initial fixed head contractor cost.'}
                            </Text>
                        </View>

                        <View style={styles.inputGroup}>
                            <Text style={styles.label}>Phone Number (Optional)</Text>
                            <TextInput
                                style={styles.input}
                                value={phone}
                                onChangeText={setPhone}
                                keyboardType="phone-pad"
                                placeholder="+91 00000 00000"
                                editable={!isSaving}
                                placeholderTextColor={Palette.textSecondary + '80'}
                            />
                        </View>

                        <View style={styles.inputGroup}>
                            <Text style={styles.label}>Notes</Text>
                            <TextInput
                                style={[styles.input, styles.textArea]}
                                value={notes}
                                onChangeText={setNotes}
                                multiline
                                numberOfLines={3}
                                placeholder="Any specific terms or notes..."
                                editable={!isSaving}
                                placeholderTextColor={Palette.textSecondary + '80'}
                            />
                        </View>

                        <TouchableOpacity 
                            style={[styles.saveButton, isSaving && { opacity: 0.7 }]} 
                            onPress={handleSave}
                            disabled={isSaving}
                        >
                            <Text style={styles.saveButtonText}>
                                {isSaving ? 'Adding...' : 'Add Staff Member'}
                            </Text>
                        </TouchableOpacity>
                        
                        <View style={{ height: 40 }} />
                    </ScrollView>
                </KeyboardAvoidingView>
            </View>
        </Modal>
    );
}

const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: 'white',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        maxHeight: '90%',
        padding: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    title: {
        fontSize: 24,
        fontFamily: 'Outfit-Bold',
        color: Palette.text,
    },
    closeButton: {
        padding: 4,
    },
    form: {
        // Remove fixed height, let content define it up to maxHeight
    },
    inputGroup: {
        marginBottom: 20,
    },
    label: {
        fontSize: 14,
        fontFamily: 'Outfit-Medium',
        color: Palette.textSecondary,
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        fontFamily: 'Outfit',
        color: Palette.text,
        borderWidth: 1,
        borderColor: '#F1F5F9',
    },
    textArea: {
        height: 80,
        textAlignVertical: 'top',
    },
    typeSelector: {
        flexDirection: 'row',
        backgroundColor: '#F1F5F9',
        padding: 4,
        borderRadius: 12,
    },
    typeButton: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 10,
    },
    activeTypeButton: {
        backgroundColor: 'white',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    typeButtonText: {
        fontSize: 13,
        fontFamily: 'Outfit-Medium',
        color: Palette.textSecondary,
    },
    activeTypeButtonText: {
        color: Palette.primary,
        fontFamily: 'Outfit-Bold',
    },
    hint: {
        fontSize: 11,
        color: Palette.textSecondary,
        fontFamily: 'Outfit',
        marginTop: 6,
        paddingHorizontal: 4,
    },
    saveButton: {
        backgroundColor: Palette.primary,
        borderRadius: 16,
        padding: 18,
        alignItems: 'center',
        marginTop: 10,
        shadowColor: Palette.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    saveButtonText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Outfit-Bold',
    },
});
