import React, { useState, useEffect } from 'react';
import {
    Modal,
    View,
    StyleSheet,
    TextInput,
    TouchableOpacity,
    KeyboardAvoidingView,
    Platform,
    Alert,
} from 'react-native';
import { Text } from './Themed';
import { Palette } from '@/constants/Colors';
import { Ionicons } from '@expo/vector-icons';
import { LaborProfile, LaborTransaction, LaborTransactionType } from '@/types/farm';

interface LaborTransactionModalProps {
    visible: boolean;
    onClose: () => void;
    onSave: (transaction: LaborTransaction) => Promise<void>;
    worker: LaborProfile;
    initialAmount?: number;
    advancePending?: number;
    wagesDue?: number;
}

export function LaborTransactionModal({ 
    visible, 
    onClose, 
    onSave, 
    worker, 
    initialAmount = 0,
    advancePending = 0,
    wagesDue = 0
}: LaborTransactionModalProps) {
    const [amount, setAmount] = useState('');
    const [type, setType] = useState<LaborTransactionType>('Advance');
    const [note, setNote] = useState('');
    const [repaymentMethod, setRepaymentMethod] = useState<'Cash' | 'Wage Income'>('Cash');
    const [isSaving, setIsSaving] = useState(false);

    const sheetType = worker.type;

    useEffect(() => {
        if (visible) {
            // Default types based on staff category
            if (sheetType === 'Daily') {
                setType('Weekly Settle');
            } else if (sheetType === 'Annual') {
                setType('Annual Installment');
            } else {
                setType('Contract Payment');
            }
            
            setAmount(initialAmount > 0 ? String(initialAmount) : '');
            setNote('');
            setIsSaving(false);
        }
    }, [visible, worker, initialAmount]);

    const handleSave = async () => {
        const amt = parseFloat(amount);
        if (isNaN(amt) || amt <= 0) {
            Alert.alert('Error', 'Please enter a valid amount');
            return;
        }

        try {
            setIsSaving(true);
            const transaction: LaborTransaction = {
                id: '', // Generated by Supabase
                workerId: worker.id,
                amount: amt,
                type,
                date: new Date().toISOString().split('T')[0],
                note: note.trim() || (type === 'Advance Repayment' ? `Repayment (${repaymentMethod})` : undefined),
            };

            await onSave(transaction);
            onClose();
        } catch (error) {
            Alert.alert('Error', 'Failed to save transaction');
        } finally {
            setIsSaving(false);
        }
    };

    const types = sheetType === 'Daily' ? 
        (['Weekly Settle', 'Advance', 'Advance Repayment'] as const) :
        sheetType === 'Annual' ? 
        (['Annual Installment', 'Salary Deduction'] as const) : 
        (['Contract Payment', 'Advance'] as const);

    return (
        <Modal
            visible={visible}
            animationType="slide"
            transparent={true}
            onRequestClose={onClose}
        >
            <View style={styles.modalOverlay}>
                <KeyboardAvoidingView
                    behavior={Platform.OS === 'ios' ? 'padding' : undefined}
                    style={styles.modalContent}
                >
                    <View style={styles.header}>
                        <View>
                            <Text style={styles.title}>Record Transaction</Text>
                            <Text style={styles.subTitle}>{worker.name}</Text>
                        </View>
                        <TouchableOpacity onPress={onClose} style={styles.closeButton} disabled={isSaving}>
                            <Ionicons name="close" size={24} color={Palette.text} />
                        </TouchableOpacity>
                    </View>

                    <View style={styles.statsRow}>
                        <View style={styles.statBox}>
                            <Text style={styles.statLabel}>{sheetType === 'Annual' ? 'Amount to Cut' : 'Wages Due'}</Text>
                            <Text style={[styles.statValue, { color: sheetType === 'Annual' ? Palette.danger : Palette.success }]}>₹{wagesDue.toLocaleString()}</Text>
                        </View>
                        <View style={styles.statDivider} />
                        <View style={styles.statBox}>
                            <Text style={styles.statLabel}>Adv. Pending</Text>
                            <Text style={[styles.statValue, { color: Palette.danger }]}>₹{advancePending.toLocaleString()}</Text>
                        </View>
                    </View>

                    <View style={styles.typeSelector}>
                        {types.map((t) => (
                            <TouchableOpacity
                                key={t}
                                style={[styles.typeBtn, type === t && styles.activeTypeBtn]}
                                onPress={() => setType(t)}
                                disabled={isSaving}
                            >
                                <Text style={[styles.typeBtnText, type === t && styles.activeTypeBtnText]}>
                                    {t === 'Weekly Settle' ? 'Settle' : 
                                     t === 'Annual Installment' ? 'Payment' :
                                     t === 'Salary Deduction' ? 'Deduction' : 
                                     t === 'Contract Payment' ? 'Progress' :
                                     t === 'Advance Repayment' ? 'Repay' : t}
                                </Text>
                            </TouchableOpacity>
                        ))}
                    </View>

                    <View style={styles.inputSection}>
                        <View style={styles.amountInputRow}>
                            <Text style={styles.currency}>₹</Text>
                            <TextInput
                                style={styles.amountInput}
                                value={amount}
                                onChangeText={setAmount}
                                keyboardType="numeric"
                                placeholder="0.00"
                                placeholderTextColor={Palette.textSecondary + '60'}
                                autoFocus
                                editable={!isSaving}
                            />
                        </View>

                        {type === 'Advance Repayment' && (
                            <View style={styles.methodToggle}>
                                {(['Cash', 'Wage Income'] as const).map((m) => (
                                    <TouchableOpacity 
                                        key={m}
                                        style={[styles.methodBtn, repaymentMethod === m && styles.activeMethodBtn]}
                                        onPress={() => setRepaymentMethod(m)}
                                    >
                                        <Text style={[styles.methodText, repaymentMethod === m && styles.activeMethodText]}>
                                            {m === 'Wage Income' ? (sheetType === 'Annual' ? 'Salary Cut' : 'Wage Income') : m}
                                        </Text>
                                    </TouchableOpacity>
                                ))}
                            </View>
                        )}

                        <TextInput
                            style={styles.noteInput}
                            value={note}
                            onChangeText={setNote}
                            placeholder="Add payment notes (Optional)..."
                            placeholderTextColor={Palette.textSecondary + '70'}
                            multiline
                            editable={!isSaving}
                        />
                    </View>

                    <TouchableOpacity 
                        style={[styles.saveButton, isSaving && { opacity: 0.7 }]} 
                        onPress={handleSave}
                        disabled={isSaving}
                    >
                        <Text style={styles.saveButtonText}>
                            {isSaving ? 'Processing...' : 'Confirm Transaction'}
                        </Text>
                    </TouchableOpacity>
                </KeyboardAvoidingView>
            </View>
        </Modal>
    );
}

const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: 'white',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 20,
    },
    title: {
        fontSize: 20,
        fontFamily: 'Outfit-Bold',
        color: Palette.text,
    },
    subTitle: {
        fontSize: 14,
        fontFamily: 'Outfit',
        color: Palette.textSecondary,
        marginTop: 2,
    },
    closeButton: {
        padding: 4,
    },
    statsRow: {
        flexDirection: 'row',
        backgroundColor: '#F8FAFC',
        padding: 16,
        borderRadius: 16,
        marginBottom: 24,
        alignItems: 'center',
    },
    statBox: {
        flex: 1,
        alignItems: 'center',
    },
    statLabel: {
        fontSize: 11,
        fontFamily: 'Outfit',
        color: Palette.textSecondary,
        textTransform: 'uppercase',
    },
    statValue: {
        fontSize: 15,
        fontFamily: 'Outfit-Bold',
        color: Palette.text,
        marginTop: 4,
    },
    statDivider: {
        width: 1,
        height: 20,
        backgroundColor: '#E2E8F0',
    },
    typeSelector: {
        flexDirection: 'row',
        backgroundColor: '#F1F5F9',
        padding: 4,
        borderRadius: 12,
        marginBottom: 24,
    },
    typeBtn: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 10,
    },
    activeTypeBtn: {
        backgroundColor: 'white',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    typeBtnText: {
        fontSize: 13,
        fontFamily: 'Outfit-Medium',
        color: Palette.textSecondary,
    },
    activeTypeBtnText: {
        fontFamily: 'Outfit-Bold',
        color: Palette.primary,
    },
    inputSection: {
        marginBottom: 24,
    },
    amountInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    currency: {
        fontSize: 32,
        fontFamily: 'Outfit-Bold',
        color: Palette.text,
        marginRight: 8,
    },
    amountInput: {
        fontSize: 48,
        fontFamily: 'Outfit-Bold',
        color: Palette.text,
        minWidth: 100,
        textAlign: 'center',
    },
    paymentSubText: {
        fontSize: 12,
        color: Palette.textSecondary,
        fontFamily: 'Outfit',
        textAlign: 'center',
        marginBottom: 20,
    },
    methodToggle: {
        flexDirection: 'row',
        marginBottom: 20,
        gap: 12,
    },
    methodBtn: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        alignItems: 'center',
    },
    activeMethodBtn: {
        backgroundColor: Palette.primary,
        borderColor: Palette.primary,
    },
    methodText: {
        fontSize: 13,
        fontFamily: 'Outfit-Medium',
        color: Palette.textSecondary,
    },
    activeMethodText: {
        color: 'white',
        fontFamily: 'Outfit-Bold',
    },
    noteInput: {
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
        padding: 16,
        fontSize: 15,
        fontFamily: 'Outfit',
        color: Palette.text,
        borderWidth: 1,
        borderColor: '#F1F5F9',
        height: 80,
        textAlignVertical: 'top',
    },
    saveButton: {
        backgroundColor: Palette.primary,
        borderRadius: 16,
        padding: 18,
        alignItems: 'center',
        shadowColor: Palette.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    saveButtonText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Outfit-Bold',
    },
});
